language: fortran90

sudo: required
dist: trusty

branches:
    only:
        - master

before_script:
    - "sudo apt get install numdiff perl cmake gcc gfortran libhdf5-serial-dev"
    - mkdir build && cd build
    - cmake ..

script:
    - make
